name: Child Action

on:
  workflow_run:
    workflows:
      - "Parent Action"
    types:
      - completed

jobs:
  child:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: value-artifact

      - name: Print value from parent action
        run: echo "Value from parent action is $(cat value.txt)"

