name: Child Action

on:
  workflow_run:
    workflows:
      - "Parent Action"
    types:
      - completed

jobs:
  entry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print value from parent action
        run: echo "Value from parent action is ${{ needs.parent.outputs.value }}"

  child:
    needs: entry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Some other step
        run: echo "This is another step in the child action"
