name: Child Action

on:
  workflow_run:
    workflows:
      - Parent Action
    types:
      - completed

jobs:
  child:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });

            const artifact = response.data.artifacts.find(a => a.name === 'value-artifact');

            if (artifact) {
              await github.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
                archive_format: 'zip',
                download_path: '.'
              });
            } else {
              throw new Error('Unable to find the value-artifact in the parent workflow.');
            }

      - name: Print value from parent action
        run: echo "Value from parent action is $(cat value.txt)"
