name: Parent Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set value in parent action
        run: echo "Handsome Hunk" > value.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: value-artifact
          path: value.txt
